### ISSUE TITLE
مشكلة التثبيت عند أستخدام صدفة zsh 

### ISSUE THREAD

**Issue by me00001** [yalang/ya#19]
السلام عليكم 
لدي مشكلة عند التثبيت

طريقة التثبيت كانت مثل الأتي 
[https://github.com/yalang/ya#installation](url)

الإختلاف الوحيد هو إضافة سطر 
>  export PATH=$HOME/ya/bin:$PATH

.bashrc بدل ملف .zshrc الى ملف

[$]  ./install.sh 
cp: cannot stat 'bin/*': No such file or directory
cp: cannot stat 'src/*': No such file or directory
cp: cannot stat 'start.py': No such file or directory
mv: cannot stat '/home/suliman/ya/bin/cmd.sh': No such file or directory
chmod: cannot access '/home/suliman/ya/bin/ya': No such file or directory
ln: failed to access '/home/suliman/ya/bin/ya': No such file or directory
Installation successful
التثبيت بنجاح
Next Add 'export PATH=/home/suliman/ya/bin:$PATH' to your .bash_profile or .bashrc
 '.bash_profile أو .bashrc  إلى 'export PATH=/home/suliman/ya/bin:$PATH' التالي أضف

# عند محاولة تشغيل اللغة أحصل على التالي 

[$]  ي
zsh: ي: command not found...
`

ألقيت نظرة بعد التثبيت على محتويات ملف
~/ya
وكان فارغًا 
وهنا الناتج 
    

`
[$]  ls -al ~/ya ~/ya/bin ~/ya/src
/home/suliman/ya:
total 20
drwxrwxr-x.  2 suliman suliman 4096 يناير  26 18:51 bin
drwxrwxr-x.  2 suliman suliman 4096 يناير  26 18:51 src
drwxrwxr-x.  4 suliman suliman 4096 يناير  26 18:51 .
drwx--x---+ 70 suliman suliman 4096 يناير  26 19:09 ..

/home/suliman/ya/bin:
total 8
drwxrwxr-x. 2 suliman suliman 4096 يناير  26 18:51 .
drwxrwxr-x. 4 suliman suliman 4096 يناير  26 18:51 ..

/home/suliman/ya/src:
total 8
drwxrwxr-x. 2 suliman suliman 4096 يناير  26 18:51 .
drwxrwxr-x. 4 suliman suliman 4096 يناير  26 18:51 ..

`

**Comment by quadrixm** [comment]
وعليكم السلام
can you tell me which operating system you are using

**Comment by me00001** [comment]
> وعليكم السلام
> can you tell me which operating system you are using

GNU/Linux Fedora 29

**Comment by quadrixm** [comment]
Can you please take a fresh checkout and install again. If same problem occur please run `./install.sh` as root.
To root login use
`su root` 
and then root password

You can also try
` ./easy_install.sh`

Remember you don't have to add path now anywhere. Just take check and run `./install.sh` or ` ./easy_install.sh` that it.

Please let me know if didn't work or if it works please let me know how.

**Comment by me00001** [comment]
> Can you please take a fresh checkout and install again. If same problem occur please run `./install.sh` as root.
> To root login use
> `su root`
> and then root password
> 
> You can also try
> ` ./easy_install.sh`
> 
> Remember you don't have to add path now anywhere. Just take check and run `./install.sh` or ` ./easy_install.sh` that it.
> 
> Please let me know if didn't work or if it works please let me know how.

لم يعمل ويضهر هذا الخطأ 
![2019-01-30 21-44-56](https://user-images.githubusercontent.com/37930867/52005447-c6e6dd80-24da-11e9-9d94-86f115901213.png)


(root) بعد تسجيل الدخول كجذر    
أصبح يعمل :+1:
![2019-01-30 21-53-42](https://user-images.githubusercontent.com/37930867/52005454-ccdcbe80-24da-11e9-9a21-d32d5bcbaf82.png)



شكرًا على المساعدة :)

**Comment by quadrixm** [comment]
مرحبا بك
